// Code generated by cmd/gen; DO NOT EDIT.
//go:generate go run ../../cmd/gen/main.go
package bridge

type Client string

// register Clients
const (
	ClientBiliClient Client = "bili"
	ClientBUPTClient Client = "bupt"
	ClientSaikrClient Client = "saikr"
)
// const register

var SupportedClients = map[Client]bool{
	ClientBiliClient: true,
	ClientBUPTClient: true,
	ClientSaikrClient: true,
}
// map register
// end register
