// Code generated by cmd/gen; DO NOT EDIT.
//go:generate go run ../../cmd/gen/main.go
package bridge

type Client string

// register Clients
const (
	ClientBiliClient Client = "bili"
	ClientBUPTClient Client = "bupt"
	ClientSaikrClient Client = "saikr"
	ClientCMathcClient Client = "cmathc"
	ClientNuedcClient Client = "nuedc"
	ClientBVFClient Client = "bvf"
	ClientCSUClient Client = "csu"
)
// const register

var SupportedClients = map[Client]bool{
	ClientBiliClient: true,
	ClientBUPTClient: true,
	ClientSaikrClient: true,
	ClientCMathcClient: true,
	ClientNuedcClient: true,
	ClientBVFClient: true,
	ClientCSUClient: true,
}
// map register
// end register
